### ISSUE TITLE
Best performing hyper-parameters and number of parameters

### ISSUE THREAD

**Issue by Demirrr** [ibalazevic/HypER#8]
Dear Ivana,

thank you for great works [1,3,4] among many others. I was wondering whether one could find the best performing hyper parameters for Hyper along with the number of parameters of it. 

I reckon that it would be beneficial for everyone if a table reporting best performing hyper parameters and respective number of model parameters  --including Hyper, MuRP and TuckER were available.

Cheers,

[1] Hypernetwork Knowledge Graph Embeddings
[2] Multi-relational Poincaré graph embeddings
[3] TuckER: Tensor Factorization for Knowledge Graph Completion

**Comment by ibalazevic** [comment]
Hi Caglar, really sorry for the late response, I must have somehow missed this. Unfortunately I haven't had time lately to do this, but I will do it if I find some time.
